#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bilibili_demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ygf
    driver-class-name: com.mysql.jdbc.Driver